# Generated by Django 4.2.20 on 2025-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMRServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=255)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('credentials', models.CharField(max_length=255)),
                ('last_claim_id', models.IntegerField(default=0)),
            ],
        ),
    ]
